name: Bug Report
description: File a bug report to help us improve munbox
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: version
    attributes:
      label: munbox Version
      description: What version of munbox are you running?
      placeholder: e.g., 1.0.0, commit hash, or "latest main"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other (please specify in description)
    validations:
      required: true

  - type: input
    id: compiler
    attributes:
      label: Compiler
      description: What compiler and version are you using?
      placeholder: e.g., GCC 13.3.0, Clang 15.0.0, MSVC 2022

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. With file '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: textarea
    id: file_info
    attributes:
      label: File Information
      description: If the issue is with a specific archive file, please provide details
      placeholder: |
        - File format (e.g., .sit, .hqx, .cpt)
        - File size
        - Source/origin of the file
        - Any error messages

  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Please copy and paste any relevant log output or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true